version: '1.0.{build}'
configuration:
- Debug
platform: Any CPU
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore "FSharpLu.Json/FSharpLu.Json.fsproj" -v Minimal
build_script:
- dotnet build "FSharpLu.Json/FSharpLu.Json.fsproj" -c %CONFIGURATION% --version-suffix %LABEL%
artifacts:
- path: '**\*.nupkg'
cache:
- '%USERPROFILE%\.nuget\packages'
